//! AuthRoute build helper. Generates `deploy/` manifests from the Rust CRD
//! types so the YAML never drifts from the source of truth (ADR-0007).
//!
//! Usage: `cargo run -p xtask -- codegen` (or just `cargo run -p xtask`).
//! RBAC generation is a TODO for M3, once the controller declares its watches.

use std::path::{Path, PathBuf};

use authroute_api::AuthPolicy;
use kube::CustomResourceExt;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cmd = std::env::args().nth(1).unwrap_or_else(|| "codegen".into());
    match cmd.as_str() {
        "codegen" => codegen(),
        other => Err(format!("unknown xtask command {other:?}; expected `codegen`").into()),
    }
}

fn codegen() -> Result<(), Box<dyn std::error::Error>> {
    let crds_dir = workspace_root().join("deploy").join("crds");
    std::fs::create_dir_all(&crds_dir)?;

    let path = crds_dir.join("authroute.dev_authpolicies.yaml");
    let yaml = serde_yaml::to_string(&AuthPolicy::crd())?;
    let contents = format!(
        "# Generated by `cargo run -p xtask -- codegen`. Do not edit by hand.\n{yaml}"
    );
    std::fs::write(&path, contents)?;
    println!("wrote {}", path.display());
    Ok(())
}

/// The workspace root, derived from this crate's manifest dir (`<root>/xtask`).
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("xtask lives at <root>/crates/xtask")
        .to_path_buf()
}
