//! Runtime configuration for the AuthRoute admission webhook (ADR-0006, ADR-0008).

/// Address the HTTPS admission server binds to. Matches the chart's webhook
/// `containerPort` (8443). Overridable for local runs.
pub const LISTEN_ADDR_ENV: &str = "AUTHROUTE_WEBHOOK_ADDR";

/// Fallback listen address when [`LISTEN_ADDR_ENV`] is unset.
pub const DEFAULT_LISTEN_ADDR: &str = "0.0.0.0:8443";

/// The webhook's own namespace, injected by the chart via the downward API
/// (`fieldRef: metadata.namespace`). Determines the serving cert's SAN and the
/// Service DNS the API server dials.
pub const NAMESPACE_ENV: &str = "AUTHROUTE_NAMESPACE";

/// Fallback namespace when [`NAMESPACE_ENV`] is unset (matches the manifests
/// generated by `xtask`).
pub const DEFAULT_NAMESPACE: &str = "authroute-system";

/// Name of the `Service` fronting this webhook, and of the
/// `ValidatingWebhookConfiguration` whose `caBundle` we patch at startup. The
/// `xtask`-generated manifests use this single name throughout.
pub const NAME: &str = "authroute-webhook";

/// HTTP path the admission server serves the review on. Must match the
/// `clientConfig.service.path` in the `ValidatingWebhookConfiguration`.
pub const VALIDATE_PATH: &str = "/validate";

/// Resolve the listen address from [`LISTEN_ADDR_ENV`], else the default.
pub fn listen_addr() -> String {
    std::env::var(LISTEN_ADDR_ENV).unwrap_or_else(|_| DEFAULT_LISTEN_ADDR.to_string())
}

/// Resolve the webhook's namespace from [`NAMESPACE_ENV`], else the default.
pub fn namespace() -> String {
    std::env::var(NAMESPACE_ENV).unwrap_or_else(|_| DEFAULT_NAMESPACE.to_string())
}

/// The DNS SANs the serving cert must carry so the API server's TLS check passes:
/// the in-cluster Service names for [`NAME`] in `namespace`.
pub fn serving_dns_names(namespace: &str) -> Vec<String> {
    vec![
        format!("{NAME}.{namespace}.svc"),
        format!("{NAME}.{namespace}.svc.cluster.local"),
    ]
}